### ISSUE TITLE
做微服务改造时 遇到一些问题 

### ISSUE THREAD

**Issue by WillemJiang** [apache/incubator-servicecomb-java-chassis#210]
@DragonTeeth 提到了一些有关使用Java-Chassis进行微服务改造遇到的问题：

背景：
原来的工程使用的是原生的 httpclient ，在改造成ServiceStage的restTemplate时遇到了一些问题。麻烦看看这些问题是否可以解决。

uam发布服务接口，目前碰到如下问题：
1、ServletOutputStream不行，必须使用确定的类，接口或抽象类不能使用
2、响应对象中有Object不行，包括Map<String,Object>这种
3、重载方法不行，方法名称必须不重复
4、方法参数名称必须是确定的对象，不能用接口或者抽象类

这个是今天发现的问题
一个controller中提供的接口过多出现如下错误：
Bad Request, description: http: request body too large。
导致启动失败。
测试的controller里大概有10来方法。

另外，遇到个问题，之前写测试方法的时候是通的，
今儿全部不通了，一直是如下错误：
java.lang.Error: not support def type: class io.swagger.models.properties.BaseIntegerProperty
日志上看没到服务端，直接在客户端就出错了。

**Comment by qizha** [comment]
所有问题的答案总结在这里了：https://huawei-servicecomb.gitbooks.io/developerguide/content/build-provider/interface-constraints.html
请参考

**Comment by lijasonvip** [comment]
@WillemJiang, thanks for your kind attention, this issue will be closed before next Monday if there is no further question about it, because all unsolved issues will be moved to Apache JIRA in next Mondy. Anyway, you can still follow us or open an issue at Apache JIRA https://issues.apache.org/jira/projects/SCB Thanks again!
