### ISSUE TITLE
What is the difference between samples and demo under root directory. It is so confused. :)

### ISSUE THREAD

**Issue by wldandan** [apache/incubator-servicecomb-java-chassis#221]

**Comment by WillemJiang** [comment]
Demo has lots of integration test cases which are more complicated for user to start as the first place.  We just  add some example as a quick start to let  people to know better about the project.

**Comment by wujimin** [comment]
https://servicecomb.atlassian.net/browse/JAV-507

**Comment by lijasonvip** [comment]
@wldandan, thanks for your kind attention, this issue will be closed before next Monday if there is no further question about it, because all unsolved issues will be moved to Apache JIRA in next Mondy. Anyway, you can still follow us or open an issue at Apache JIRA https://issues.apache.org/jira/projects/SCB Thanks again!

**Comment by zhengyangyong** [comment]
samples : examples for show development
demo : be used for integration test with docker (will pull up one producer and one consuer)
integration-tests : also be used for integration test with spring boot runner
