### ISSUE TITLE
服务端和消费端的启动入口类是哪个？

### ISSUE THREAD

**Issue by lorgine** [apache/incubator-servicecomb-java-chassis#240]
Rt。

**Comment by eric-lee-ltk** [comment]
启动入口类是`CseApplicationListener`，它是通过事件来触发启动和销毁的。如何启动和销毁这个可以参考`integration-tests`模块下面的`springmvc-tests`和`spring-springmvc-tests`模块中的`BeforeClass`和`AfterClass`中的用法。

**Comment by lijasonvip** [comment]
@lorgine, thanks for your kind attention, this issue will be closed before next Monday if there is no further question about it, because all unsolved issues will be moved to Apache JIRA in next Mondy. Anyway, you can still follow us or open an issue at Apache JIRA https://issues.apache.org/jira/projects/SCB Thanks again!

**Comment by zhengyangyong** [comment]
@lorgine Please check samples under source code,  also you can get more information from : http://servicecomb.incubator.apache.org/users/application-boot-process/
