### ISSUE TITLE
对ServiceComb中RestSchema的一些诉求

### ISSUE THREAD

**Issue by DragonTeeth** [apache/incubator-servicecomb-java-chassis#252]
我们现在使用的是iio.servicecomb.provider.rest.common中的RestSchema,
在使用过程中发现它对我们原SpringMVC的兼容不够，希望ServiceComb能兼容一下。
具体的使用场景如下：
1. 方法的响应类型是object的。启动工程都会报错。io.servicecomb.foundation.common.exceptions.ServiceCombException: java.lang.Object not support. Must be a concrete type
2. controller 里面有方法重载。即方法名一致但是 参数和RequestMapping 里面的method不一样这个也是兼容不了的，这个在SpringMCV里面很常见。

**Comment by WillemJiang** [comment]
@DragonTeeth 多谢提出的问题。 

第一个问题，Object返回值太通用的， 这是一个很不好的使用方式， 因为服务的提供方和消费方无法根据Object来进行契约验证，所以ServiceComb不支持Object返回值，请明确指明返回值类型。 
第二个问题，目前还ServiceComb内部还支持直接感知参数名重载的问题，这部分的问题可以通过修改方法名的方式绕过去， 后续我们会对这部分的内容进行进一步的优化。

**Comment by seanyinx** [comment]
这个问题可以参考 https://github.com/ServiceComb/ServiceComb-Java-Chassis/issues/210 里的回答

**Comment by MabinGo** [comment]
@qizha @WillemJiang @wujimin 各位大神，对于业务代码存在方法响应类型包含object、抽象类、重载的场景，在技术上是否有考虑支持方案？

**Comment by lijasonvip** [comment]
@DragonTeeth, To get more information about your question you can check issue: https://github.com/ApacheInfra/ServiceComb-Java-Chassis/issues/210,  thanks for your kind attention, this issue will be closed before next Monday if there is no further question about it, because all unsolved issues will be moved to Apache JIRA in next Mondy. Anyway, you can still follow us or open an issue at Apache JIRA https://issues.apache.org/jira/projects/SCB Thanks again!

**Comment by zhengyangyong** [comment]
Hi @DragonTeeth  , if you had any question, please contact us again, thanks!
