### ISSUE TITLE
按照文档根本搭建不起来一个可以使用的服务

### ISSUE THREAD

**Issue by xiaoshao** [apache/incubator-servicecomb-java-chassis#335]
咋们的文档中压根就没提java-chassis-dependencies加入到dependency management里面。导致服务根本启动不了。

还有咋们的文档跟sample代码有很大的区别。这个很尴尬啊。

能不能更新一下文档。个人感觉，如果按照文档一个小时搭建不起来一个微服务，使用这个框架的机会就比较渺茫了。

**Comment by WillemJiang** [comment]
请问你看的文档是在servicecomb.io 网站上的吗？ 能详细描述一下具体的问题是什么样的吗？例如文档的位置以及sample代码的名称。
文档这块我们会继续完善，也欢迎提出宝贵修改意见，如果是servicecomb.io上面的文档，可以在网页上直接提交PR进行相关的修改。

**Comment by eric-lee-ltk** [comment]
官网的快速入门目前确实还不完善，缺少说明创建模块时以pom的方式引入java-chassis-dependencies。快速入门的文档确实需要进行改进。

**Comment by lijasonvip** [comment]
@xiaoshao, thanks for your kind attention, this issue will be closed before next Monday if there is no further question about it, because all unsolved issues will be moved to Apache JIRA in next Mondy. Anyway, you can still follow us or open an issue at Apache JIRA https://issues.apache.org/jira/projects/SCB Thanks again!

**Comment by zhengyangyong** [comment]
Hello @xiaoshao ,we had provided [archetypes](https://github.com/apache/incubator-servicecomb-java-chassis/tree/master/archetypes) in order to easier startup.
Also we had improved docs，if you found any mistake, you can [submit PR](http://servicecomb.incubator.apache.org/developers/submit-codes/) to fix it , Thanks :+1:
