### ISSUE TITLE
关于暴漏rest协议,消费端项目调用最佳实践是?

### ISSUE THREAD

**Issue by kkrgwbj** [apache/incubator-servicecomb-java-chassis#807]
关于servicecomb暴漏的rest服务,有什么最佳的实践来建议用哪种方式吗?springcloud默认的是建议用feign.

**Comment by kkrgwbj** [comment]
另外,如果基于服务契约来解耦生产者和消费者项目,是不是每个服务接口都需要编写一遍契约文件?

**Comment by wujimin** [comment]
servicecomb named this: develop mode  
develop mode is to express business logic, not care for governance and transport  
currently for consumer, support:  
1.transparent rpc  
  it's similar to feign, but more simpler, because no need to write annotations  
2.RestTemplate  

different develop mode almost have the same abilities, there is no good or bad for them  
just only which one do you prefer?  
Personally, I prefer the transparent rpc

**Comment by wujimin** [comment]
servicecomb support code first mode, can generate contract from method and annotations automatically in run time

**Comment by kkrgwbj** [comment]
能否提供一个 准商用的demo

**Comment by zhengyangyong** [comment]
I think this demo may give some help : https://github.com/zhengyangyong/servicecomb-demo-feign
